name: Start #name action
run-name: Start hello run name #run name
on:
  push:
    branches:
      - feat/ci-cd

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Step heello
        run: |
          ls
          echo "hello"
          node -v