name: BE-CI
run-name: BE-CI

on:
  pull_request:
    branches:
      - 'develop'
    paths:
        - backend/**
defaults:
  run:
    working-directory: ./backend
jobs:
  run-quanlity-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Using docker to check convention code
        run: |
          echo "Start lint...."
          echo "Install tool..." #Install tool if github action is not built-in
          npm install -g eslint
          eslint *.js --fix
          docker run -i --rm -v $(pwd):/app/source -v $(pwd)/.prettierrc:/app/.prettierrc hocptit/eslint-ci:0.0.1 "."
          echo "Lint done."


  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run unit test
        run: |
          echo "Start run...."
          echo "Install tool..." #Install tool if github action is not built-in
          npx jest
          echo "Run done."